/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_miniBeta_2 (
    input clk,
    input rst,
    input custom_start_button,
    input ls_1,
    input ls_1F,
    input ls_2,
    input ls_2F,
    input ls_3,
    input ls_3F,
    input ls_4,
    input ls_4F,
    output reg [15:0] timer_out,
    output reg [15:0] score_out,
    output reg [15:0] ball_count,
    output reg debug_slowclock
  );
  
  
  
  reg [15:0] inputAlu_a;
  
  reg [15:0] inputAlu_b;
  
  wire [16-1:0] M_game_alu_out;
  wire [1-1:0] M_game_alu_z;
  wire [1-1:0] M_game_alu_v;
  wire [1-1:0] M_game_alu_n;
  reg [6-1:0] M_game_alu_alufn_signal;
  reg [16-1:0] M_game_alu_a;
  reg [16-1:0] M_game_alu_b;
  alu_11 game_alu (
    .alufn_signal(M_game_alu_alufn_signal),
    .a(M_game_alu_a),
    .b(M_game_alu_b),
    .out(M_game_alu_out),
    .z(M_game_alu_z),
    .v(M_game_alu_v),
    .n(M_game_alu_n)
  );
  
  wire [1-1:0] M_edge_dt_slowtimer_out;
  reg [1-1:0] M_edge_dt_slowtimer_in;
  edge_detector_4 edge_dt_slowtimer (
    .clk(clk),
    .in(M_edge_dt_slowtimer_in),
    .out(M_edge_dt_slowtimer_out)
  );
  wire [6-1:0] M_game_controlunit_alufn;
  wire [3-1:0] M_game_controlunit_asel;
  wire [3-1:0] M_game_controlunit_bsel;
  wire [2-1:0] M_game_controlunit_alu_out_sel;
  wire [4-1:0] M_game_controlunit_regfile_write_address;
  wire [4-1:0] M_game_controlunit_regfile_read_address_a;
  wire [4-1:0] M_game_controlunit_regfile_read_address_b;
  wire [1-1:0] M_game_controlunit_we_regfile;
  wire [4-1:0] M_game_controlunit_debug;
  wire [1-1:0] M_game_controlunit_decimal_counter_increase;
  wire [1-1:0] M_game_controlunit_decimal_counter_rst;
  reg [1-1:0] M_game_controlunit_decrease_timer;
  reg [16-1:0] M_game_controlunit_regfile_datain;
  reg [1-1:0] M_game_controlunit_custom_start_button;
  reg [1-1:0] M_game_controlunit_ls_1;
  reg [1-1:0] M_game_controlunit_ls_1F;
  reg [1-1:0] M_game_controlunit_ls_2;
  reg [1-1:0] M_game_controlunit_ls_2F;
  reg [1-1:0] M_game_controlunit_ls_3;
  reg [1-1:0] M_game_controlunit_ls_3F;
  reg [1-1:0] M_game_controlunit_ls_4;
  reg [1-1:0] M_game_controlunit_ls_4F;
  game_CU_12 game_controlunit (
    .clk(clk),
    .rst(rst),
    .decrease_timer(M_game_controlunit_decrease_timer),
    .regfile_datain(M_game_controlunit_regfile_datain),
    .custom_start_button(M_game_controlunit_custom_start_button),
    .ls_1(M_game_controlunit_ls_1),
    .ls_1F(M_game_controlunit_ls_1F),
    .ls_2(M_game_controlunit_ls_2),
    .ls_2F(M_game_controlunit_ls_2F),
    .ls_3(M_game_controlunit_ls_3),
    .ls_3F(M_game_controlunit_ls_3F),
    .ls_4(M_game_controlunit_ls_4),
    .ls_4F(M_game_controlunit_ls_4F),
    .alufn(M_game_controlunit_alufn),
    .asel(M_game_controlunit_asel),
    .bsel(M_game_controlunit_bsel),
    .alu_out_sel(M_game_controlunit_alu_out_sel),
    .regfile_write_address(M_game_controlunit_regfile_write_address),
    .regfile_read_address_a(M_game_controlunit_regfile_read_address_a),
    .regfile_read_address_b(M_game_controlunit_regfile_read_address_b),
    .we_regfile(M_game_controlunit_we_regfile),
    .debug(M_game_controlunit_debug),
    .decimal_counter_increase(M_game_controlunit_decimal_counter_increase),
    .decimal_counter_rst(M_game_controlunit_decimal_counter_rst)
  );
  wire [16-1:0] M_regfiles_out_a;
  wire [16-1:0] M_regfiles_out_b;
  wire [16-1:0] M_regfiles_out;
  wire [16-1:0] M_regfiles_total_score;
  wire [16-1:0] M_regfiles_ball_count_out;
  reg [4-1:0] M_regfiles_write_address;
  reg [1-1:0] M_regfiles_we;
  reg [16-1:0] M_regfiles_data;
  reg [4-1:0] M_regfiles_read_address_a;
  reg [4-1:0] M_regfiles_read_address_b;
  game_miniRegfiles_13 regfiles (
    .clk(clk),
    .rst(rst),
    .write_address(M_regfiles_write_address),
    .we(M_regfiles_we),
    .data(M_regfiles_data),
    .read_address_a(M_regfiles_read_address_a),
    .read_address_b(M_regfiles_read_address_b),
    .out_a(M_regfiles_out_a),
    .out_b(M_regfiles_out_b),
    .out(M_regfiles_out),
    .total_score(M_regfiles_total_score),
    .ball_count_out(M_regfiles_ball_count_out)
  );
  wire [1-1:0] M_slow_timer_value;
  counter_14 slow_timer (
    .clk(clk),
    .rst(rst),
    .value(M_slow_timer_value)
  );
  
  always @* begin
    M_game_controlunit_custom_start_button = custom_start_button;
    M_game_controlunit_ls_1 = ls_1;
    M_game_controlunit_ls_1F = ls_1F;
    M_game_controlunit_ls_2 = ls_2;
    M_game_controlunit_ls_2F = ls_2F;
    M_game_controlunit_ls_3 = ls_3;
    M_game_controlunit_ls_3F = ls_3F;
    M_game_controlunit_ls_4 = ls_4;
    M_game_controlunit_ls_4F = ls_4F;
    M_edge_dt_slowtimer_in = M_slow_timer_value;
    M_game_controlunit_decrease_timer = M_edge_dt_slowtimer_out;
    M_regfiles_we = M_game_controlunit_we_regfile;
    M_regfiles_write_address = M_game_controlunit_regfile_write_address;
    M_regfiles_read_address_a = M_game_controlunit_regfile_read_address_a;
    M_regfiles_read_address_b = M_game_controlunit_regfile_read_address_b;
    M_game_controlunit_regfile_datain = M_regfiles_out_b;
    
    case (M_game_controlunit_asel)
      2'h0: begin
        inputAlu_a = M_regfiles_out_a;
      end
      2'h1: begin
        inputAlu_a = 6'h3c;
      end
      2'h2: begin
        inputAlu_a = 1'h1;
      end
      2'h3: begin
        inputAlu_a = 2'h2;
      end
      default: begin
        inputAlu_a = 1'h0;
      end
    endcase
    
    case (M_game_controlunit_bsel)
      2'h0: begin
        inputAlu_b = M_regfiles_out_b;
      end
      2'h1: begin
        inputAlu_b = 1'h1;
      end
      2'h2: begin
        inputAlu_b = 3'h4;
      end
      2'h3: begin
        inputAlu_b = 4'ha;
      end
      default: begin
        inputAlu_b = 1'h0;
      end
    endcase
    M_game_alu_a = inputAlu_a;
    M_game_alu_b = inputAlu_b;
    M_game_alu_alufn_signal = M_game_controlunit_alufn;
    
    case (M_game_controlunit_alu_out_sel)
      2'h1: begin
        M_regfiles_data = 16'hffff;
      end
      2'h2: begin
        M_regfiles_data = 16'h000f;
      end
      default: begin
        M_regfiles_data = M_game_alu_out;
      end
    endcase
    ball_count = M_regfiles_ball_count_out;
    timer_out = M_regfiles_out;
    score_out = M_regfiles_total_score;
    debug_slowclock = M_slow_timer_value;
  end
endmodule
