/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_16 (
    input [2:0] alufn_signal,
    input z,
    input n,
    input v,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 16'h0000;
    
    case (alufn_signal[0+1-:2])
      default: begin
        out[0+0-:1] = 1'h0;
      end
      2'h0: begin
        out[0+0-:1] = z;
      end
      2'h1: begin
        out[0+0-:1] = n ^ v;
      end
      2'h2: begin
        out[0+0-:1] = z | (n ^ v);
      end
    endcase
  end
endmodule
